name: CI
on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v3

      # Use the correct Bun setup action
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      # Install dependencies
      - run: bun install --frozen-lockfile

      # Run CI commands
      - run: bun run ci
